
export const TRAVEL_PICKUP_ROUTES = {
    ROOT: '/',
    LOGIN: '/login',
    AUTH: {
        ROOT: '/auth',
        PARAMS: {
            PROVIDER: ':provider'
        }
    },
    PICKUPS: {
        ROOT: '/pickups',
        HOME: 'home',
        CENTER: 'centers',
        ENROL: 'enrol',
        COMPLETE: 'complete',
        PARAMS: {
            PICKUP_ID: ':pickupId'
        }
    },
    NOT_FOUND: '*'
}

export const TRAVEL_PICKUP_PATHS = {
    ROOT: TRAVEL_PICKUP_ROUTES.ROOT,
    LOGIN: TRAVEL_PICKUP_ROUTES.LOGIN,
    AUTH: TRAVEL_PICKUP_ROUTES.AUTH.ROOT,
    AUTH_PARAMS: `${TRAVEL_PICKUP_ROUTES.AUTH.ROOT}/`,
    PICKUPS: TRAVEL_PICKUP_ROUTES.PICKUPS.ROOT,
    PICKUPS_HOME: `${TRAVEL_PICKUP_ROUTES.PICKUPS.ROOT}/${TRAVEL_PICKUP_ROUTES.PICKUPS.HOME}`,
    PICKUPS_CENTER: `${TRAVEL_PICKUP_ROUTES.PICKUPS}/${TRAVEL_PICKUP_ROUTES.PICKUPS.CENTER}`,
    PICKUPS_ENROL: `${TRAVEL_PICKUP_ROUTES.PICKUPS.ROOT}/${TRAVEL_PICKUP_ROUTES.PICKUPS.ENROL}`,
    PICKUPS_COMPLETE: `${TRAVEL_PICKUP_ROUTES.PICKUPS.ROOT}/${TRAVEL_PICKUP_ROUTES.PICKUPS.COMPLETE}`,
    PICKUPS_PARAMS: `${TRAVEL_PICKUP_ROUTES.PICKUPS.ROOT}/`
}
